2024-03-20 18:14:00,118 ERROR: Exception on /reset_password_request [GET] [in D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\dev\workspace\iten-engineering\dbwe\flask\blog11\blog.py", line 256, in reset_password_request
    return render_template('reset_password_request.html', form=form)
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\dev\workspace\iten-engineering\dbwe\flask\blog11\templates\reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\dev\workspace\iten-engineering\dbwe\flask\blog11\templates\base.html", line 20, in top-level template code
    {% block content %}
  File "D:\dev\workspace\iten-engineering\dbwe\flask\blog11\templates\reset_password_request.html", line 10, in block 'content'
    {% for error in form.username.errors %}
  File "D:\dev\software\miniconda3\envs\dbwe\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'forms.ResetPasswordRequestForm object' has no attribute 'username'
